import { Sparkles } from "lucide-react";
import { format, parseISO } from "date-fns";

interface InsightSummaryProps {
  summary: string
  month: string
  generatedAt: string
}

export function InsightSummary({ summary, month, generatedAt }: InsightSummaryProps) {
  const monthDate = parseISO(month);
  const monthLabel = format(monthDate, "MMMM yyyy");

  const generatedDate = parseISO(generatedAt);
  const now = new Date();
  const isToday =
    generatedDate.getDate() === now.getDate() &&
    generatedDate.getMonth() === now.getMonth() &&
    generatedDate.getFullYear() === now.getFullYear();

  const timeStr = format(generatedDate, "h:mm a");
  const generatedLabel = isToday
    ? `Generated today at ${timeStr}`
    : `Generated on ${format(generatedDate, "MMM d")} at ${timeStr}`;

  return (
    <div
      className="bg-[#1A1A1E] rounded-xl border border-[rgba(255,255,255,0.06)] border-l-[3px] border-l-[#7C6EF7] p-6 mb-6"
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-2">
          <Sparkles size={16} className="text-[#7C6EF7]" />
          <span className="text-xs text-[#8A8A8A]">Monthly Summary</span>
        </div>
        <span className="text-xs px-2 py-1 rounded-md bg-[#7C6EF7]/10 text-[#7C6EF7] flex items-center gap-1">
          <Sparkles size={10} />
          Generated by AI
        </span>
      </div>

      <p className="text-[11px] text-[#8A8A8A] mb-2">{monthLabel}</p>

      <p className="text-[15px] text-[#F0EFE9] leading-relaxed">
        {summary}
      </p>

      <p className="text-[11px] text-[#8A8A8A] mt-3">{generatedLabel}</p>
    </div>
  );
}