import { Sparkles, TrendingUp, TrendingDown, AlertCircle } from 'lucide-react';
import { LineChart, Line, ResponsiveContainer } from 'recharts';

const sparklineData = [
  { value: 850 },
  { value: 920 },
  { value: 1150 },
  { value: 980 },
  { value: 1340 },
  { value: 1120 },
  { value: 1580 },
];

const insights = [
  {
    id: 1,
    type: 'warning',
    title: 'Dining out is up 40% this month',
    description: 'You\'ve spent ₱8,500 on food this month, compared to ₱6,100 last month. Consider meal prepping to save.',
    trend: 'up',
    sparkline: sparklineData,
  },
  {
    id: 2,
    type: 'positive',
    title: 'You\'re on track to save ₱4,200 this month',
    description: 'At your current pace, you\'ll have ₱4,200 left over. Keep it up!',
    trend: 'positive',
  },
  {
    id: 3,
    type: 'alert',
    title: '3 subscriptions you haven\'t used in 30 days',
    description: 'You\'re paying ₱847/month for unused subscriptions. Consider canceling:',
    subscriptions: [
      { name: 'Netflix Premium', amount: 549 },
      { name: 'Spotify Premium', amount: 149 },
      { name: 'Adobe Creative Cloud', amount: 149 },
    ],
  },
];

export function Insights() {
  return (
    <div className="p-8">
      <div className="mb-8">
        <h2 className="text-2xl font-medium mb-1" style={{ fontFamily: 'var(--font-display)' }}>
          Insights
        </h2>
        <p className="text-text-secondary text-sm">AI-powered financial insights and recommendations</p>
      </div>

      <div className="bg-surface rounded-xl p-6 border border-border border-l-4 border-l-primary shadow-sm mb-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-2">
            <Sparkles size={18} className="text-primary" />
            <span className="text-xs text-text-secondary">Monthly Summary</span>
          </div>
          <span className="text-xs px-2 py-1 bg-primary/20 text-primary rounded-md">Generated by AI</span>
        </div>
        <p className="text-lg italic leading-relaxed text-foreground" style={{ fontFamily: 'Georgia, serif' }}>
          "You're doing great this month, Alex. Your spending is down 12% compared to last month, and you're
          on track to meet your savings goal. However, I noticed a spike in dining expenses — perhaps consider
          cooking at home a few more times this week. Overall, you're building solid financial habits."
        </p>
      </div>

      <div className="space-y-4">
        {insights.map((insight) => (
          <div
            key={insight.id}
            className="bg-surface rounded-xl p-6 border border-border shadow-sm hover:border-border/60 transition-colors"
          >
            <div className="flex items-start gap-4">
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${
                  insight.type === 'warning'
                    ? 'bg-destructive/20'
                    : insight.type === 'positive'
                    ? 'bg-secondary/20'
                    : 'bg-primary/20'
                }`}
              >
                {insight.type === 'warning' && <TrendingUp size={18} className="text-destructive" />}
                {insight.type === 'positive' && <TrendingDown size={18} className="text-secondary" />}
                {insight.type === 'alert' && <AlertCircle size={18} className="text-primary" />}
              </div>

              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-4 mb-2">
                  <h3 className="text-base font-medium text-foreground">{insight.title}</h3>
                  {insight.sparkline && (
                    <div className="w-24 h-8 flex-shrink-0">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={insight.sparkline}>
                          <Line
                            type="monotone"
                            dataKey="value"
                            stroke="#FF6B6B"
                            strokeWidth={2}
                            dot={false}
                          />
                        </LineChart>
                      </ResponsiveContainer>
                    </div>
                  )}
                </div>
                <p className="text-sm text-text-secondary leading-relaxed mb-3">{insight.description}</p>

                {insight.subscriptions && (
                  <div className="space-y-2 mt-3">
                    {insight.subscriptions.map((sub, index) => (
                      <div
                        key={index}
                        className="flex items-center justify-between py-2 px-3 bg-background rounded-lg"
                      >
                        <span className="text-sm text-foreground">{sub.name}</span>
                        <span className="text-sm text-text-secondary" style={{ fontFamily: 'var(--font-mono)' }}>
                          ₱{sub.amount}/mo
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 bg-surface rounded-xl p-6 border border-border shadow-sm">
        <h3 className="text-lg font-medium mb-4">Quick tips</h3>
        <div className="space-y-3">
          <div className="flex items-start gap-3">
            <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0"></div>
            <p className="text-sm text-text-secondary">
              Set up automatic transfers to savings on payday to make saving effortless
            </p>
          </div>
          <div className="flex items-start gap-3">
            <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0"></div>
            <p className="text-sm text-text-secondary">
              Review your subscriptions quarterly to avoid paying for services you don't use
            </p>
          </div>
          <div className="flex items-start gap-3">
            <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0"></div>
            <p className="text-sm text-text-secondary">
              Use the 50/30/20 rule: 50% needs, 30% wants, 20% savings and debt repayment
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
