// Category example phrases used to compute embedding centroids.
// These are NOT shown to the user — only used internally to build
// representative category embeddings.
//
// Each category has 5-10 example phrases covering different ways
// users might describe a transaction in that category.
//
// IMPORTANT: Keys MUST match the `categories` table in the database exactly.
// Current DB categories: Food, Transport, Utilities, Shopping, Health, Housing, Entertainment,
//                       Travel, Savings, Loan, Business, Transfer, Gifts, Investments,
//                       Salary, Freelance

export const categoryExamples: Record<string, string[]> = {
  'Food': [
    'restaurant meal',
    'groceries',
    'dining out',
    'lunch',
    'dinner',
    'snacks',
    'fast food',
    'coffee shop',
    'food delivery',
    'breakfast',
    'meryenda',
    'bring your own food',
  ],
  'Transport': [
    'taxi ride',
    'ride share',
    'bus fare',
    'train ticket',
    'gas refill',
    'parking fee',
    'toll fee',
    'motorcycle fuel',
    'flight ticket',
    'car maintenance',
    'jeepney ride',
    'tricycle fare',
  ],
  'Utilities': [
    'electricity bill',
    'water bill',
    'internet bill',
    'phone bill',
    'subscription fee',
    'insurance payment',
    'utility payment',
    'streaming subscription',
    'telco load',
    'postpaid plan',
  ],
  'Loan': [
    'loan payment',
    'debt repayment',
    'car loan installment',
    'housing loan',
    'personal loan payment',
    'bank amortization',
    'credit card payment',
  ],
  'Business': [
    'office supplies',
    'business supplies',
    'inventory purchase',
    'wholesale purchase',
    'printing expense',
    'business permit renewal',
    'supplier payment',
  ],
  'Transfer': [
    'bank transfer',
    'fund transfer',
    'money sent',
    'instapay transfer',
    'pesonet transfer',
    'gcash send',
    'digital wallet transfer',
  ],
  'Shopping': [
    'clothing purchase',
    'online shopping',
    'electronics purchase',
    'accessories',
    'department store',
    'shoe purchase',
    'beauty product',
    'cosmetics',
    'skincare',
    'salon visit',
    'haircut',
    'nail spa',
    'personal care item',
  ],
  'Health': [
    'doctor visit',
    'medicine purchase',
    'pharmacy',
    'gym membership',
    'health checkup',
    'dental visit',
    'vitamins and supplements',
    'hospital bill',
    'laboratory test',
    'veterinary visit',
    'pet supplies',
    'pet grooming',
    'pet food',
  ],
  'Housing': [
    'monthly rent',
    'mortgage payment',
    'furniture purchase',
    'home repair',
    'apartment deposit',
    'home appliance',
    'moving cost',
    'association dues',
    'cleaning service',
    'laundry expense',
  ],
  'Entertainment': [
    'movie ticket',
    'streaming subscription',
    'video game',
    'concert ticket',
    'sports event',
    'hobby purchase',
    'book purchase',
    'mobile legend',
    'gaming purchase',
    'karaoke',
  ],
  'Travel': [
    'hotel booking',
    'vacation expense',
    'flight booking',
    'travel insurance',
    'tourist activity',
    'luggage purchase',
    'resort stay',
    'ferry ticket',
    'tour package',
    'commute',
  ],
  'Savings': [
    'savings deposit',
    'emergency fund transfer',
    'money set aside',
    'sss contribution',
    'pag-ibig contribution',
    'philhealth contribution',
    'time deposit',
    'coin bank savings',
  ],
  'Investments': [
    'stock purchase',
    'mutual fund',
    'cryptocurrency purchase',
    'investment deposit',
    'uitf investment',
    'bond purchase',
    'real estate investment',
    'col financial',
  ],
  'Gifts': [
    'donation',
    'charity contribution',
    'tithe',
    'gift given to someone',
    'church offering',
    'birthday gift',
    'wedding gift',
    'sponsorship',
  ],
  'Salary': [
    'salary received',
    'payroll credit',
    'bonus received',
    'refund received',
    'cashback',
    'allowance received',
    'reimbursement',
    'wage payment',
  ],
  'Freelance': [
    'freelance payment',
    'upwork income',
    'fiverr earnings',
    'online job payment',
    'virtual assistant pay',
    'outsourcing income',
  ],
};